---
- name: Stop and disable timer
  ansible.builtin.systemd:
    name: "container-splatnet2statink-{{ item.name }}.timer"
    scope: user
    enabled: no
    state: stopped
  loop: "{{ splatnet2statink_config }}"

- name: Stop and disable timer for salmon
  ansible.builtin.systemd:
    name: "container-splatnet2statink-{{ item.name }}-salmon.timer"
    scope: user
    enabled: no
    state: stopped
  when: item.salmon | default(False)
  loop: "{{ splatnet2statink_config }}"

- name: Stop service
  ansible.builtin.systemd:
    name: "container-splatnet2statink-{{ item.name }}.service"
    scope: user
    state: stopped
  loop: "{{ splatnet2statink_config }}"

- name: Stop service for salmon
  ansible.builtin.systemd:
    name: "container-splatnet2statink-{{ item.name }}-salmon.service"
    scope: user
    state: stopped
  when: item.salmon | default(False)
  loop: "{{ splatnet2statink_config }}"

- name: Delete timer unit file
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/systemd/user/container-splatnet2statink-{{ item.name }}.timer"
    state: absent
  loop: "{{ splatnet2statink_config }}"

- name: Delete service unit file
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/systemd/user/container-splatnet2statink-{{ item.name }}.service"
    state: absent
  loop: "{{ splatnet2statink_config }}"

- name: Delete timer unit file for salmon
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/systemd/user/container-splatnet2statink-{{ item.name }}-salmon.timer"
    state: absent
  when: item.salmon | default(False)
  loop: "{{ splatnet2statink_config }}"

- name: Delete service unit file for salmon
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/systemd/user/container-splatnet2statink-{{ item.name }}-salmon.service"
    state: absent
  when: item.salmon | default(False)
  loop: "{{ splatnet2statink_config }}"

- name: Reload systemd
  ansible.builtin.systemd:
    scope: user
    daemon_reload: yes

- name: Delete splatnet2statink container
  containers.podman.podman_container:
    name: "splatnet2statink-{{ item.name }}"
    state: absent
  loop: "{{ splatnet2statink_config }}"

- name: Delete splatnet2statink container for salmon
  containers.podman.podman_container:
    name: "splatnet2statink-{{ item.name }}-salmon"
    state: absent
  when: item.salmon | default(False)
  loop: "{{ splatnet2statink_config }}"

- name: Delete splatnet2statink directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/splatnet2statink"
    state: absent

