FROM docker.io/library/python:3.10-buster AS builder
WORKDIR /
COPY requirements.txt /
RUN pip install -r requirements.txt

FROM docker.io/library/python:3.10-slim
WORKDIR /app
COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages
COPY dbs.py /app
COPY iksm.py /app
COPY salmonrun.py /app
COPY splatnet2statink.py /app
CMD [ "python", "splatnet2statink.py" ]

